### PR TITLE
Moved Files + Better README

### PR DESCRIPTION
**Pull request by kierajreed**
What do you guys think?

### CODE REVIEW

**Comment by ThybeVB** [comment]
Good jOA

**Comment by Laz-The-Artist** [comment]
okay

**Comment by kierajreed** [comment]
Should I merge?

**Comment by kierajreed** [comment]
well great

**Comment by ThybeVB** [comment]
gg

**Comment by kierajreed** [comment]
leave the branch though

**Comment by ThybeVB** [comment]
Aight

**Pull request merged**
